export const starterReference = {
  id: 'starter',
  name: 'Blank playable',
  details: 'Reference: 1080 x 1920 blank, element-only playable layout',
  defaults: {
    canvas: {
      width: 1080,
      height: 1920,
      scalePosition: 'center',
    },
    background: {
      mode: 'color',
      color: '#ffffff',
      image: '',
      fit: 'cover',
      opacity: 1,
    },
    overlay: {
      enabled: false,
      showInPreview: true,
      color: '#000000',
      opacity: 0.35,
      blur: 0,
      image: '',
      fit: 'cover',
    },
    endScene: {
      enabled: false,
      name: 'End Scene',
      html: '',
      clickUrl: '',
      showOnLoad: false,
      delaySeconds: 0.95,
      animation: 'slide-right',
    },
    body: {
      enabled: false,
      mode: 'text',
      title: 'Main content',
      subtitle: 'Use this area for the playable body.',
      accent: '#d1d5db',
      panel: '#e5e7eb',
      textColor: '#4b5563',
      image: '',
      imageFit: 'cover',
      x: 90,
      y: 430,
      width: 900,
      height: 900,
    },
    elements: [],
    header: {
      enabled: false,
      name: 'Header',
      mode: 'text',
      title: 'Logo here',
      tagline: 'Tagline here',
      image: '',
      imageWidth: 125,
      fullWidth: false,
      background: '#ffffff',
      x: 90,
      y: 120,
      width: 900,
      height: 220,
      align: 'center',
      color: '#4b5563',
      size: 72,
    },
    cta: {
      enabled: false,
      name: 'CTA',
      text: 'Continue',
      x: 240,
      y: 1588,
      width: 600,
      height: 140,
      radius: 28,
      color: '#e5e7eb',
      textColor: '#374151',
      animation: 'ping',
      speed: 1.35,
    },
  },
}
